name: Build and Deploy
on:
  push:
    branches:
      - master
      - main
      - zos-support-8
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: wget remote website
      run: |
        sudo apt-get update -y
        sudo apt-get upgrade -y
        ./contrib/download_prerequisites
        echo "prerequisits done"
        sudo apt-get install -y libgmp3-dev libmpfr-dev libmpfr-doc
        git clone https://github.com/LukasJaks/gcc-zos.git
        cd gcc-zos
        chmod +x configure
        echo "done"
        ./configure
        echo "configure done"
        make
        echo "make done"
        make install
        echo "done"
