name: Build and Deploy
on:
  commit:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: wget remote website
      run: |
        git clone https://github.com/LukasJaks/gcc-zos.git
        cd gcc-zos
        chmod +x configure
        ./configure
