name: Build and Deploy
on:
  push:
    branches:
      - master
      - main
      - zos-support-8
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: wget remote website
      run: |
        apt-get install -y libgmp3-dev libmpfr-dev libmpfr-doc libmpfr4 libmpfr4-dbg mpc
        git clone https://github.com/LukasJaks/gcc-zos.git
        cd gcc-zos
        chmod +x configure
        ./configure
